/**
 * Represents an apartment listing in the real estate application.
 * This interface defines the structure of apartment data stored in the database.
 */
export interface Apartment {
  /** Unique identifier for the apartment (auto-generated by MongoDB) */
  _id: string;
  
  /** Name of the apartment unit (e.g., "Luxury Penthouse Suite") */
  unitName: string;
  
  /** Unit number or identifier (e.g., "A101", "B205") */
  unitNumber: string;
  
  /** Name of the project or building complex */
  project: string;
  
  /** Price of the apartment in the base currency */
  price: number;
  
  /** Number of bedrooms in the apartment */
  bedrooms: number;
  
  /** Number of bathrooms in the apartment */
  bathrooms: number;
  
  /** Size of the apartment in square feet */
  size: number;
  
  /** Detailed description of the apartment features and amenities */
  description: string;
  
  /** Optional URL to an image of the apartment */
  imageUrl?: string;
  
  /** Timestamp when the apartment was created (auto-generated) */
  createdAt: Date;
  
  /** Timestamp when the apartment was last updated (auto-generated) */
  updatedAt: Date;
}



/**
 * Query parameters for filtering apartments
 */
export interface ApartmentQueryParams {
  /** Search term for unit name or unit number */
  search?: string;
  
  /** Filter by project name */
  project?: string;
  
  /** Minimum price filter */
  minPrice?: string;
  
  /** Maximum price filter */
  maxPrice?: string;
}