/**
 * Represents an apartment listing in the frontend application.
 * This interface matches the backend Apartment type structure.
 */
export interface Apartment {
  /** Unique identifier for the apartment (auto-generated by MongoDB) */
  _id: string;
  
  /** Name of the apartment unit (e.g., "Luxury Penthouse Suite") */
  unitName: string;
  
  /** Unit number or identifier (e.g., "A101", "B205") */
  unitNumber: string;
  
  /** Name of the project or building complex */
  project: string;
  
  /** Price of the apartment in the base currency */
  price: number;
  
  /** Number of bedrooms in the apartment */
  bedrooms: number;
  
  /** Number of bathrooms in the apartment */
  bathrooms: number;
  
  /** Size of the apartment in square feet */
  size: number;
  
  /** Detailed description of the apartment features and amenities */
  description: string;
  
  /** Optional URL to an image of the apartment */
  imageUrl?: string;
  
  /** Timestamp when the apartment was created (auto-generated) */
  createdAt: string;
  
  /** Timestamp when the apartment was last updated (auto-generated) */
  updatedAt: string;
}



/**
 * Query parameters for filtering apartments
 */
export interface ApartmentQueryParams {
  /** Search term for unit name or unit number */
  search?: string;
  
  /** Filter by project name */
  project?: string;
  
  /** Minimum price filter */
  minPrice?: string;
  
  /** Maximum price filter */
  maxPrice?: string;
}

/**
 * API response wrapper for consistent response structure
 */
export interface ApiResponse<T> {
  /** Indicates if the request was successful */
  success: boolean;
  
  /** Response data (present on success) */
  data?: T;
  
  /** Error message (present on failure) */
  error?: string;
  
  /** Additional error details (present on validation errors) */
  details?: string[];
  
  /** Response message (present on success) */
  message?: string;
  
  /** Count of items (present on list responses) */
  count?: number;
  
  /** Applied filters (present on list responses) */
  filters?: ApartmentQueryParams;
}

/**
 * Form validation errors for apartment creation/editing
 */
export interface ApartmentFormErrors {
  unitName?: string;
  unitNumber?: string;
  project?: string;
  price?: string;
  bedrooms?: string;
  bathrooms?: string;
  size?: string;
  description?: string;
  imageUrl?: string;
  general?: string;
}